#ifndef MAIN_TASKS_COMMON_H_
#define MAIN_TASKS_COMMON_H_

// WIFI SNTP TASK
#define WIFI_TASK_STACK_SIZE 4096
#define WIFI_TASK_PRIORITY 3
#define WIFI_TASK_CORE_ID 0

// LCD SPI TASK
#define LCD_SPI_TASK_STACK_SIZE 4096
#define LCD_SPI_TASK_PRIORITY 3
#define LCD_SPI_TASK_CORE_ID 1

#endif // MAIN_TASKS_COMMON_H_